// 全屏触发代码（无问题，保留)
function lydecode(a){
    // 修复：初始化转换后的代码
    let finalCode = a;

    const lanyueCodeList = [
        // ===== DOM文档对象基础 =====
        '文档.',
        '主体.',
        '窗口.',
        '警告(',
        '控制台打印(',
        '确认弹窗(',
        '输入弹窗(',
        '获取元素(',
        '查询选择器(',
        '查询全部(',
        '创建元素(',
        '追加子节点(',
        '移除子节点(',
        '获取父节点',
        '获取子节点',
        'HTML内容=',
        '文本内容=',
        '样式.',
        '类列表.',
        '添加类名(',
        '移除类名(',
        '切换类名(',
        '是否包含类名(',
        '设置属性(',
        '获取属性(',
        '删除属性(',
        // ===== 路径与跳转 =====
        '地址.',
        '链接到=',
        '打开(',
        '重新加载(',
        // ===== 本地存储 =====
        '声明变量',
        '声明常量',
        
        // ===== JS 控制流 =====
        '声明函数',
        '返回值',
        '如果(',
        '否则如果(',
        '否则{',
        '尝试{',
        '捕捉错误(',
        '抛出错误(',
        '循环开始(',
        '当循环(',
        '继续循环;',
        '终止循环;',
        '真',
        '假',
        '空值',
        '未定义',
        // ===== 定时器 =====
        '定时执行(',
        '延时执行(',
        '清除定时(',
        '清除延时(',
        // ===== 事件 =====
        '添加事件监听器(',
        '移除事件监听器(',
        '按下执行=',
        '鼠标点击事件',
        '鼠标移入事件',
        '鼠标移出事件',
        '鼠标按下事件',
        '鼠标松开事件',
        '键盘按下事件',
        '键盘松开事件',
        '拒绝默认事件(',
        '阻止冒泡(',
        // ===== 数组与对象 =====
        '数组长度',
        '数组推入(',
        '数组弹出()',
        '数组移位()',
        '数组取消移位(',
        '数组切片(',
        '数组过滤(',
        '数组映射(',
        '数组遍历(',
        // ===== Fetch网络请求 =====
        '网络请求(',
        '转为JSON()',
        '文本读取()',
        // ===== Canvas画布 =====
        '获取2D画布(',
        '设置填充色=',
        '设置描边色=',
        '开始绘制()',
        '结束绘制()',
        '绘制矩形(',
        '填充矩形(',
        '清除矩形(',
        '绘制文字(',
        // ===== HTML 根结构标签 =====
        '<HTML',
        'HTML>',
        '<元数据',
        '元数据>',
        '头部>',
        '<头部',
        '<主体',
        '主体>',
        '<容器',
        '容器>',
        '<部分',
        '部分>',
        '<上部',
        '上部>',
        '<主要内容',
        '主要内容>',
        '<页脚',
        '页脚>',
        '<导航栏',
        '导航栏>',
        '<表单',
        '表单>',
        // ===== 文本标签 =====
        '大标题>',
        '<大标题',
        '副标题>',
        '<副标题',
        '小标题>',
        '<小标题',
        '段落>',
        '超链接>',
        '<超链接',
        '粗体>',
        '斜体>',
        '下划线>',
        '删除线>',
        '引用>',
        '行内代码>',
        '代码块>',
        '换行>',
        '水平分割线>',
        // ===== 媒体 & 资源标签 =====
        '<图片',
        'PNG图片',
        'SVG图片',
        '<视频',
        '视频>',
        'audio>',
        '<音频',
        '<链接',
        '图标',
        'WOFF2字体',
        '<脚本',
        '脚本>',
        // ===== 表单组件 =====
        '<输入框',
        '输入框>',
        '<按钮',
        '按钮>',
        '下拉选择>',
        '<下拉选择',
        '文本域>',
        '<文本域',
        '"提交"',
        // ===== HTML 属性 =====
        '唯一标识=',
        'CSS类=',
        '名称=',
        '资源链接=',
        '输入提示=',
        '标题=',
        '字符设置="',
        '语言="英文"',
        '类别="',
        '类型="',
        '尺寸="',
        '视口',
        '内容=',
        '设备宽度',
        '初始缩放=',
        '作为=',
        '跨域=',
        '匿名',
        '"字体"',
        '"样式表"',
        '目标窗口=',
        '跳转地址=',
        '禁用',
        '只读',
        '必填',
        '值=',
        '选中',
        '自动聚焦',
        // ===== CSS 内联样式 =====
        '内联样式>',
        '字号:',
        '像素;',
        '宽度:',
        '高度:',
        '宽度=',
        '高度=',
        '背景颜色:',
        '文字颜色:',
        '字体粗细:',
        '文本对齐:',
        '行高:',
        '外边距:',
        '内边距:',
        '边框:',
        '圆角:',
        '阴影:',
        '显示模式:',
        '定位方式:',
        '左偏移:',
        '上偏移:',
        '透明度:',
        '过渡动画:',
        '溢出处理:',
        '光标样式:',
        '字体家族:',
        '文字装饰:',
        '弹性布局方向:',
        '水平对齐:',
        '垂直对齐:',
        // ===== SVG 基础 =====
        '<动画',
        '动画>',
        '<路径',
        '路径>',
        'SVG宽度=',
        'SVG高度=',
        'SVG视盒=',
        '填充颜色=',
        '描边颜色=',
        '描边宽度=',
        // ===== 转义占位符 =====
        '转义占位符',
        // ============================================================
    // ============ 以下为新增映射块（追加在末尾） ============
    // ============================================================

    // ===== DOM 补充 =====
    '节点前插入(',
    '替换子节点(',
    '克隆节点(',
    '获取滚动位置',
    '滚动到(',
    '获取元素位置',
    '获取元素尺寸',
    '聚焦()',
    '失焦()',
    '提交表单()',
    '重置表单()',
    '检查元素是否包含(',
    '最近匹配元素(',
    '获取兄弟节点',
    '获取下一个兄弟',
    '获取上一个兄弟',
    '设置光标位置(',
    '滚动到顶部',
    '滚动到底部',
    '页面滚动X',
    '页面滚动Y',
    '窗口宽度',
    '窗口高度',
    '设备像素比',

    // ===== 字符串 =====
    '字符串长度',
    '字符串截取(',
    '字符串查找(',
    '字符串替换(',
    '字符串分割(',
    '字符串转大写()',
    '字符串转小写()',
    '字符串去空格()',
    '字符串包含(',
    '字符串开头是(',
    '字符串结尾是(',
    '字符串重复(',
    '字符串填充开头(',
    '字符串填充结尾(',
    '字符串索引位置(',

    // ===== 数字与数学 =====
    '随机小数()',
    '随机整数(',
    '向上取整(',
    '向下取整(',
    '四舍五入(',
    '最大值(',
    '最小值(',
    '绝对值(',
    '幂运算(',
    '开平方(',
    '圆周率',
    '自然常数',

    // ===== 日期时间 =====
    '当前时间()',
    '创建日期(',
    '获取年份()',
    '获取月份()',
    '获取日期()',
    '获取星期()',
    '获取小时()',
    '获取分钟()',
    '获取秒数()',
    '时间戳()',
    '格式化日期(',
    '解析日期(',

    // ===== 本地/会话存储 =====
    '本地存储设置(',
    '本地存储获取(',
    '本地存储删除(',
    '本地存储清空()',
    '会话存储设置(',
    '会话存储获取(',
    '会话存储删除(',

    // ===== 数组补充 =====
    '数组连接(',
    '数组查找元素(',
    '数组查找索引(',
    '数组排序()',
    '数组反转()',
    '数组包含(',
    '数组归约(',
    '数组连接成字符串(',
    '数组去重()',
    '数组 every(',
    '数组 some(',
    '数组填充(',
    '数组平坦化()',

    // ===== 异步与 Promise =====
    '新Promise(',
    '异步函数',
    '等待 ',
    '全部Promise完成(',
    'Promise竞速(',
    '延迟等待(',
    '转JSON字符串(',
    '解析JSON(',

    // ===== 剪贴板 =====
    '复制到剪贴板(',
    '读取剪贴板()',

    // ===== 浏览历史 =====
    '前进()',
    '后退()',
    '历史记录长度',
    '跳转历史(',

    // ===== 事件补充 =====
    '双击事件',
    '滚轮事件',
    '右键菜单事件',
    '变更事件',
    '输入事件',
    '表单提交事件',
    '页面加载完成事件',
    '窗口大小改变事件',
    '窗口滚动事件',
    '拖拽开始事件',
    '拖拽结束事件',
    '拖拽进入事件',
    '拖拽离开事件',
    '放置事件',
    '获取焦点事件',
    '失去焦点事件',
    '按键按下持续事件',

    // ===== Canvas 补充 =====
    '绘制圆(',
    '绘制弧(',
    '绘制直线(',
    '绘制二次贝塞尔(',
    '绘制三次贝塞尔(',
    '平移画布(',
    '旋转画布(',
    '缩放画布(',
    '保存画布状态()',
    '恢复画布状态()',
    '创建线性渐变(',
    '创建径向渐变(',
    '渐变添加色标(',
    '绘制图片(',
    '线条宽度=',
    '线条端点=',
    '线条连接=',
    '设置阴影颜色=',
    '设置阴影偏移X=',
    '设置阴影偏移Y=',
    '设置阴影模糊=',
    '设置全局透明度=',
    '设置合成模式=',
    '测量文字宽度(',

    // ===== SVG 补充 =====
    'SVG圆形',
    'SVG矩形',
    'SVG线条',
    'SVG多边形',
    'SVG文本',
    'SVG组',
    'SVG圆心=',
    'SVG半径=',
    'SVG终点X=',
    'SVG终点Y=',
    'SVG点列表=',
    'SVG变换=',
    'SVG文字内容=',
    'SVG字体大小=',
    'SVG文字对齐=',

    // ===== HTML 标签补充 =====
    '<无序列表',
    '无序列表>',
    '<有序列表',
    '列表项>',
    '<表格',
    '表格>',
    '<表格行',
    '表格行>',
    '<表头单元格',
    '表头单元格>',
    '<表格单元格',
    '表格单元格>',
    '<标签',
    '标签>',
    '<下拉选项',
    '下拉选项>',
    '<预定义',
    '预定义>',
    '<范围滑块',
    '范围滑块>',
    '<颜色选择器',
    '<日期选择器',
    '<隐藏域',
    '<侧边栏',
    '侧边栏>',
    '<分隔内容',
    '<对话框',
    '对话框>',
    '<进度条',
    '进度条>',
    '<计量条',
    '<图片地图',
    '<热点区域',

    // ===== HTML 属性补充 =====
    '多选',
    '多行',
    '自动完成=',
    '自动播放',
    '循环播放',
    '控制面板',
    '预加载=',
    '替代文本=',
    '图片地图=',
    '快捷键=',
    '下拉分组=',
    '选项值=',
    '选项是否选中',
    '步长=',
    '最小值=',
    '最大值=',
    '起始值=',
    '结束值=',
    '打开状态',
    '懒加载',
    '编码类型=',
    '提交方式=',
    '表单关联=',
    '标签关联=',

    // ===== CSS 补充（布局） =====
    '弹性换行:',
    '弹性间距:',
    '对齐内容:',
    '对齐项目:',
    '对齐自身:',
    '网格布局:',
    '网格列数:',
    '网格行数:',
    '网格间距:',
    '间隙:',
    '固定定位',
    '绝对定位',
    '相对定位',
    '静态定位',
    '层级:',
    '指针事件:',
    '用户选择:',
    '可见性:',
    '最小宽度:',
    '最大宽度:',
    '最小高度:',
    '最大高度:',
    '溢出-x:',
    '溢出-y:',
    '白空间:',
    '文字换行:',
    '弹性增长:',
    '弹性收缩:',
    '弹性基准:',
    '顺序:',
    '变换:',
    '变换原点:',
    '动画:',
    '关键帧名称:',
    '动画时长:',
    '动画缓动:',
    '动画延迟:',
    '动画次数:',
    '动画方向:',
    '填充模式:',

    // ===== CSS 补充（视觉） =====
    '背景图片:',
    '背景重复:',
    '背景大小:',
    '背景位置:',
    '背景渐变(',
    '文字阴影:',
    '列表样式:',
    '列表位置:',
    '边框宽度:',
    '边框样式:',
    '边框颜色:',
    '边框-collapse:',
    '字体样式:',
    '字间距:',
    '词间距:',
    '首行缩进:',
    '垂直对齐:',
    '对象适配:',
    '对象位置:',
    '外观:',
    '轮廓:',
    '轮廓偏移:',
    '换行方式:',
    '缩放:',
    '滤镜:',
    '混合模式:',
    '剪裁路径:',
    '遮罩:',

    // ===== 转义占位符 =====
    '转义占位符'
    ];

    const JavaScriptList = [
        // ===== DOM文档对象基础 =====
        'document.',
        'body.',
        'window.',
        'alert(',
        'console.log(',
        'confirm(',
        'prompt(',
        'getElementById(',
        'querySelector(',
        'querySelectorAll(',
        'createElement(',
        'appendChild(',
        'removeChild(',
        '.parentElement',
        '.children',
        'innerHTML=',
        'textContent=',
        'style.',
        'classList.',
        'add(',
        'remove(',
        'toggle(',
        'contains(',
        'setAttribute(',
        'getAttribute(',
        'removeAttribute(',
        // ===== 路径与跳转 =====
        'location.',
        'href=',
        'open(',
        'reload(',
        // ===== 本地存储 =====
        'let',
        'const',
        
        // ===== JS 控制流 =====
        'function',
        'return',
        'if(',
        'else if(',
        'else{',
        'try{',
        'catch(',
        'throw(',
        'for(',
        'while(',
        'continue;',
        'break;',
        'true',
        'false',
        'null',
        'undefined',
        // ===== 定时器 =====
        'setInterval(',
        'setTimeout(',
        'clearInterval(',
        'clearTimeout(',
        // ===== 事件 =====
        'addEventListener(',
        'removeEventListener(',
        'onclick=',
        '"click"',
        '"mouseover"',
        '"mouseout"',
        '"mousedown"',
        '"mouseup"',
        '"keydown"',
        '"keyup"',
        'preventDefault(',
        'stopPropagation(',
        // ===== 数组与对象 =====
        '.length',
        '.push(',
        '.pop()',
        '.shift()',
        '.unshift(',
        '.slice(',
        '.filter(',
        '.map(',
        '.forEach(',
        // ===== Fetch网络请求 =====
        'fetch(',
        '.json()',
        '.text()',
        // ===== Canvas画布 =====
        'getContext(\'2d\')',
        'fillStyle=',
        'strokeStyle=',
        'beginPath()',
        'closePath()',
        'rect(',
        'fillRect(',
        'clearRect(',
        'fillText(',
        // ===== HTML 根结构标签 =====
        '<html',
        'html>',
        '<meta',
        'meta>',
        'head>',
        '<head',
        '<body',
        'body>',
        '<div',
        'div>',
        '<section',
        'section>',
        '<header',
        'header>',
        '<main',
        'main>',
        '<footer',
        'footer>',
        '<nav',
        'nav>',
        '<form',
        'form>',
        // ===== 文本标签 =====
        'h1>',
        '<h1',
        'h2>',
        '<h2',
        'h3>',
        '<h3',
        'p>',
        '<a',
        'a>',
        'b>',
        'i>',
        'u>',
        'del>',
        'q>',
        'code>',
        'pre>',
        '<br',
        '<hr',
        // ===== 媒体 & 资源标签 =====
        '<img',
        'image/png',
        'image/svg+xml',
        '<video muted',
        'video>',
        'audio>',
        '<audio',
        '<link',
        'icon',
        'font/woff2',
        '<script',
        'script>',
        // ===== 表单组件 =====
        '<input',
        'input>',
        '<button',
        'button>',
        'select>',
        '<select',
        'textarea>',
        '<textarea',
        '"submit"',
        // ===== HTML 属性 =====
        'id=',
        'class=',
        'name=',
        'src=',
        'placeholder=',
        'title=',
        'charset="',
        'lang="en"',
        'rel="',
        'type="',
        'sizes="',
        'viewport',
        'content=',
        'device-width',
        'initial-scale=',
        'as=',
        'crossorigin=',
        'anonymous',
        '"font"',
        '"stylesheet"',
        'target=',
        'href=',
        'disabled',
        'readonly',
        'required',
        'value=',
        'checked',
        'autofocus',
        // ===== CSS 内联样式 =====
        'style>',
        'font-size:',
        'px;',
        'width:',
        'height:',
        'width=',
        'height=',
        'background-color:',
        'color:',
        'font-weight:',
        'text-align:',
        'line-height:',
        'margin:',
        'padding:',
        'border:',
        'border-radius:',
        'box-shadow:',
        'display:',
        'position:',
        'left:',
        'top:',
        'opacity:',
        'transition:',
        'overflow:',
        'cursor:',
        'font-family:',
        'text-decoration:',
        'flex-direction:',
        'justify-content:',
        'align-items:',
        // ===== SVG 基础 =====
        '<animate',
        'animate>',
        '<path',
        'path>',
        'width=',
        'height=',
        'viewBox=',
        'fill=',
        'stroke=',
        'stroke-width=',
        // ===== 转义占位符 =====
        '%%ESCAPE%%',
        // ============================================================
    // ============ 以下为新增映射块（追加在末尾） ============
    // ============================================================

    // ===== DOM 补充 =====
    'before(',
    'replaceChild(',
    'cloneNode(',
    'getBoundingClientRect()',
    'scrollTo(',
    'offsetTop',
    'offsetWidth',
    'focus()',
    'blur()',
    'submit()',
    'reset()',
    'contains(',
    'closest(',
    '.parentNode',
    '.nextElementSibling',
    '.previousElementSibling',
    'setSelectionRange(',
    'scrollTo(0,0)',
    'scrollTo(0,document.body.scrollHeight)',
    'window.pageXOffset',
    'window.pageYOffset',
    'window.innerWidth',
    'window.innerHeight',
    'window.devicePixelRatio',

    // ===== 字符串 =====
    '.length',
    'substring(',
    'indexOf(',
    'replace(',
    'split(',
    'toUpperCase()',
    'toLowerCase()',
    'trim()',
    'includes(',
    'startsWith(',
    'endsWith(',
    'repeat(',
    'padStart(',
    'padEnd(',
    'charAt(',

    // ===== 数字与数学 =====
    'Math.random()',
    'Math.floor(Math.random()*',
    'Math.ceil(',
    'Math.floor(',
    'Math.round(',
    'Math.max(',
    'Math.min(',
    'Math.abs(',
    'Math.pow(',
    'Math.sqrt(',
    'Math.PI',
    'Math.E',

    // ===== 日期时间 =====
    'new Date()',
    'new Date(',
    'getFullYear()',
    'getMonth()+1',
    'getDate()',
    'getDay()',
    'getHours()',
    'getMinutes()',
    'getSeconds()',
    'Date.now()',
    'toLocaleDateString(',
    'Date.parse(',

    // ===== 本地/会话存储 =====
    'localStorage.setItem(',
    'localStorage.getItem(',
    'localStorage.removeItem(',
    'localStorage.clear()',
    'sessionStorage.setItem(',
    'sessionStorage.getItem(',
    'sessionStorage.removeItem(',

    // ===== 数组补充 =====
    'concat(',
    'find(',
    'findIndex(',
    'sort()',
    'reverse()',
    'includes(',
    'reduce(',
    'join(',
    '[...new Set(',
    'every(',
    'some(',
    'fill(',
    'flat()',

    // ===== 异步与 Promise =====
    'new Promise(',
    'async function',
    'await ',
    'Promise.all(',
    'Promise.race(',
    'new Promise(r=>setTimeout(r,',
    'JSON.stringify(',
    'JSON.parse(',

    // ===== 剪贴板 =====
    'navigator.clipboard.writeText(',
    'navigator.clipboard.readText()',

    // ===== 浏览历史 =====
    'history.forward()',
    'history.back()',
    'history.length',
    'history.go(',

    // ===== 事件补充 =====
    '"dblclick"',
    '"wheel"',
    '"contextmenu"',
    '"change"',
    '"input"',
    '"submit"',
    '"load"',
    '"resize"',
    '"scroll"',
    '"dragstart"',
    '"dragend"',
    '"dragenter"',
    '"dragleave"',
    '"drop"',
    '"focus"',
    '"blur"',
    '"keypress"',

    // ===== Canvas 补充 =====
    'arc(',
    'arc(',
    'moveTo(',
    'quadraticCurveTo(',
    'bezierCurveTo(',
    'translate(',
    'rotate(',
    'scale(',
    'save()',
    'restore()',
    'createLinearGradient(',
    'createRadialGradient(',
    'addColorStop(',
    'drawImage(',
    'lineWidth=',
    'lineCap=',
    'lineJoin=',
    'shadowColor=',
    'shadowOffsetX=',
    'shadowOffsetY=',
    'shadowBlur=',
    'globalAlpha=',
    'globalCompositeOperation=',
    'measureText(',

    // ===== SVG 补充 =====
    '<circle',
    '<rect',
    '<line',
    '<polygon',
    '<text',
    '<g',
    'cx=',
    'r=',
    'x2=',
    'y2=',
    'points=',
    'transform=',
    '>',
    'font-size=',
    'text-anchor=',

    // ===== HTML 标签补充 =====
    '<ul',
    'ul>',
    '<ol',
    'li>',
    '<table',
    'table>',
    '<tr',
    'tr>',
    '<th',
    'th>',
    '<td',
    'td>',
    '<label',
    'label>',
    '<optgroup',
    'option>',
    '<datalist',
    'datalist>',
    '<input type="range"',
    '<input type="color"',
    '<input type="date"',
    '<input type="hidden"',
    '<aside',
    'aside>',
    '<hr',
    '<dialog',
    'dialog>',
    '<progress',
    'progress>',
    '<meter',
    '<map',
    '<area',

    // ===== HTML 属性补充 =====
    'multiple',
    'rows=',
    'autocomplete=',
    'autoplay',
    'loop',
    'controls',
    'preload=',
    'alt=',
    'usemap=',
    'accesskey=',
    '<optgroup',
    'value=',
    'selected',
    'step=',
    'min=',
    'max=',
    'min=',
    'max=',
    'open',
    'loading="lazy"',
    'enctype=',
    'method="',
    'form=',
    'for=',

    // ===== CSS 补充（布局） =====
    'flex-wrap:',
    'gap:',
    'justify-content:',
    'align-items:',
    'align-self:',
    'display:grid',
    'grid-template-columns:',
    'grid-template-rows:',
    'grid-gap:',
    'gap:',
    'position:fixed',
    'position:absolute',
    'position:relative',
    'position:static',
    'z-index:',
    'pointer-events:',
    'user-select:',
    'visibility:',
    'min-width:',
    'max-width:',
    'min-height:',
    'max-height:',
    'overflow-x:',
    'overflow-y:',
    'white-space:',
    'word-break:',
    'flex-grow:',
    'flex-shrink:',
    'flex-basis:',
    'order:',
    'transform:',
    'transform-origin:',
    'animation:',
    'animation-name:',
    'animation-duration:',
    'animation-timing-function:',
    'animation-delay:',
    'animation-iteration-count:',
    'animation-direction:',
    'animation-fill-mode:',

    // ===== CSS 补充（视觉） =====
    'background-image:',
    'background-repeat:',
    'background-size:',
    'background-position:',
    'linear-gradient(',
    'text-shadow:',
    'list-style:',
    'list-style-position:',
    'border-width:',
    'border-style:',
    'border-color:',
    'border-collapse:',
    'font-style:',
    'letter-spacing:',
    'word-spacing:',
    'text-indent:',
    'vertical-align:',
    'object-fit:',
    'object-position:',
    'appearance:',
    'outline:',
    'outline-offset:',
    'word-wrap:',
    'zoom:',
    'filter:',
    'mix-blend-mode:',
    'clip-path:',
    'mask:',

    // ===== 转义占位符 =====
    '%%ESCAPE%%'
    ];
    // 长字符串优先替换，防止短关键字提前匹配截断长关键字
    lanyueCodeList.sort((a,b)=>b.length - a.length);
    JavaScriptList.sort((a,b)=>b.length - a.length);

    // 执行全部替换
    for(let i = 0; i < lanyueCodeList.length; i++){
        finalCode = finalCode.replaceAll(lanyueCodeList[i], JavaScriptList[i]);
    }
    // 清除转义标记
    finalCode = finalCode.replaceAll('%%ESCAPE%%','');
    return finalCode;
}
/*function sanitizeNoJump(htmlStr) {
     const dom = new DOMParser().parseFromString(htmlStr, "text/html");
     const doc = dom.documentElement;
     // 1. 删除全部 a 超链接标签（会跳转）
     doc.querySelectorAll("a").forEach(el => {
         el.replaceWith(...el.childNodes);
     });
     // 2. 删除 script 全部JS脚本
     doc.querySelectorAll("script").forEach(el => el.remove());
     // 3. 删除iframe（内嵌页面跳转）
     doc.querySelectorAll("iframe").forEach(el => el.remove());
     // 4. 删除form表单（表单提交跳转）
     doc.querySelectorAll("form").forEach(el => el.remove());
     // 5. 清除所有事件属性 onclick,onload,onerror,onmouseover...全部on*开头
     doc.querySelectorAll("*").forEach(el => {
         Array.from(el.attributes).forEach(attr => {
             const name = attr.name.toLowerCase();
             // 删除所有on事件
             if(name.startsWith("on")){
                 el.removeAttribute(name);
             }
             // 删除href、src属性，防止 javascript: 伪协议跳转
             if(["href","src","action"].includes(name)){
                 let val = attr.value.trim().toLowerCase();
                 if(val.startsWith("javascript:") || val.startsWith("vbscript:")){
                     el.removeAttribute(name);
                 }
             }
         })
     })
     // 6. 删除 meta 自动跳转标签 <meta http‑equiv="refresh">
     doc.querySelectorAll('meta[http‑equiv="refresh"]').forEach(el=>el.remove());
     // 返回body内部的HTML
     return doc.body.innerHTML;
 }*/
 // 使用示例
function decodeAndRun(a){
    eval((lydecode(a)));
}